### ISSUE TITLE
Öffi Repository und F-Droid

### ISSUE THREAD

**Issue by SecUpwN** [schildbach/oeffi.schildbach.de#2]
Guten Abend lieber Andreas, kannst Du mir sagen warum Du `Öffi` nicht als quelloffene App auf GitHub einstellst? Habe `Öffi` eigentlich immer sehr gemocht, nur spackt es auf meiner custom ROM hin und wieder rum. Außerdem frage ich mich, warum Du `Öffi` nicht auf [F-Droid](https://f-droid.org/) veröffentlichst, dann würdest Du mehr helfende Entwickler finden. Nimm's mir nicht übel, aber weil `Öffi` hier nicht zu finden ist bin ich auf der Suche nach einer *quelloffenen* Alternative und habe derzeit [Transportr](https://github.com/grote/Transportr) im Visir. Schönen Abend!

**Comment by schildbach** [comment]
Es gibt ein F-Droid-Repo unter http://oeffi.schildbach.de/fdroid/repo
